<?php

/**
 * 10 SEO odaklı Türkçe blog yazısı — BlogPostsSeeder tarafından yüklenir.
 *
 * @return list<array{
 *     slug: string,
 *     file: string,
 *     category_slug: string,
 *     title: string,
 *     meta_title: string,
 *     meta_description: string,
 *     excerpt: string,
 *     og_image: string,
 *     published_days_ago: int
 * }>
 */
return [
    [
        'slug' => 'vps-hosting-paneli-nasil-secilir',
        'file' => '01-vps-hosting-paneli-nasil-secilir.md',
        'category_slug' => 'hosting-migration',
        'title' => 'VPS hosting paneli nasıl seçilir? 2026 rehberi',
        'meta_title' => 'VPS hosting paneli nasıl seçilir? cPanel alternatifi rehberi',
        'meta_description' => 'Kendi VPS sunucunuzda hosting paneli seçerken dikkat etmeniz gerekenler: maliyet, açık kaynak, SSL, yedekleme ve ajans ihtiyaçları.',
        'excerpt' => 'Paylaşımlı hostingden VPS’e geçtiğinizde panel seçimi işinizi yıllarca şekillendirir. Gerçek ihtiyaçlarınıza göre nasıl karar vereceğinizi anlatıyoruz.',
        'og_image' => '/images/blog/vps-hosting-paneli-nasil-secilir.svg',
        'published_days_ago' => 28,
    ],
    [
        'slug' => 'lets-encrypt-ssl-hosting-panelinde',
        'file' => '02-lets-encrypt-ssl-hosting-panelinde.md',
        'category_slug' => 'security',
        'title' => 'Let\'s Encrypt SSL: hosting panelinde otomatik sertifika rehberi',
        'meta_title' => 'Let\'s Encrypt SSL kurulumu — hosting panelinde otomatik HTTPS',
        'meta_description' => 'Let\'s Encrypt ile ücretsiz SSL: DNS doğrulama, yenileme, wildcard sertifika ve panel üzerinden HTTPS açma adımları.',
        'excerpt' => 'HTTPS artık lüks değil; Let\'s Encrypt ile ücretsiz sertifika almak mümkün. Panelden otomatik kurulum ve yenileme nasıl çalışır?',
        'og_image' => '/images/blog/lets-encrypt-ssl-hosting-panelinde.svg',
        'published_days_ago' => 25,
    ],
    [
        'slug' => 'cpanel-alternatifi-acik-kaynak-hosting-paneli',
        'file' => '03-cpanel-alternatifi-acik-kaynak-hosting-paneli.md',
        'category_slug' => 'hosting-migration',
        'title' => 'cPanel alternatifi: açık kaynak hosting paneli karşılaştırması',
        'meta_title' => 'cPanel alternatifi açık kaynak hosting paneli — Panelze, CyberPanel, Hestia',
        'meta_description' => 'cPanel lisans maliyeti artınca açık kaynak panellere yönelenler için gerçekçi karşılaştırma: özellikler, öğrenme eğrisi ve toplam sahip olma maliyeti.',
        'excerpt' => 'cPanel fiyatları yükseldiğinde “acaba kendi panelimizi mi kursak?” sorusu kaçınılmaz. Açık kaynak seçenekleri dürüstçe karşılaştırdık.',
        'og_image' => '/images/blog/cpanel-alternatifi-acik-kaynak-hosting-paneli.svg',
        'published_days_ago' => 22,
    ],
    [
        'slug' => 'wordpress-hosting-nasil-secilir-kurulum',
        'file' => '04-wordpress-hosting-nasil-secilir-kurulum.md',
        'category_slug' => 'hosting-migration',
        'title' => 'WordPress hosting nasıl seçilir? Hız, güvenlik ve tek tık kurulum',
        'meta_title' => 'WordPress hosting seçimi 2026 — hız, güvenlik ve kurulum rehberi',
        'meta_description' => 'WordPress sitesi için doğru hosting: PHP 8.x, OPcache, SSL, yedekleme ve tek tık kurulum. VPS üzerinde kendi panelinizle nasıl yönetirsiniz?',
        'excerpt' => 'WordPress’in %43’ü web’de diyorlar; doğru hosting seçimi hem hız hem güvenlik demek. Pratik kontrol listesi burada.',
        'og_image' => '/images/blog/wordpress-hosting-nasil-secilir-kurulum.svg',
        'published_days_ago' => 19,
    ],
    [
        'slug' => 'sunucu-guvenligi-fail2ban-ufw-rehberi',
        'file' => '05-sunucu-guvenligi-fail2ban-ufw-rehberi.md',
        'category_slug' => 'security',
        'title' => 'Sunucu güvenliği: Fail2ban ve UFW ile temel koruma rehberi',
        'meta_title' => 'Fail2ban ve UFW sunucu güvenliği rehberi — SSH ve panel koruması',
        'meta_description' => 'Yeni VPS kurduktan sonra ilk yapmanız gerekenler: UFW firewall kuralları, Fail2ban ile brute-force engelleme ve panel erişimini sıkılaştırma.',
        'excerpt' => 'Sunucuyu açtığınız anda botlar kapıyı çalıyor. Fail2ban ve UFW ile temel ama etkili bir güvenlik katmanı nasıl kurulur?',
        'og_image' => '/images/blog/sunucu-guvenligi-fail2ban-ufw-rehberi.svg',
        'published_days_ago' => 16,
    ],
    [
        'slug' => 'git-deploy-ile-canli-site-guncelleme',
        'file' => '06-git-deploy-ile-canli-site-guncelleme.md',
        'category_slug' => 'scaling',
        'title' => 'Git deploy ile canlı site güncelleme: FTP\'ye veda',
        'meta_title' => 'Git deploy hosting — canlı siteye otomatik güncelleme rehberi',
        'meta_description' => 'FTP ile dosya atmayı bırakın: Git push ile staging ve production ortamlarına güvenli deploy. Webhook, SSH ve panel entegrasyonu.',
        'excerpt' => 'Hâlâ FileZilla ile canlıya mı atıyorsunuz? Git tabanlı deploy hem hızlı hem geri alınabilir; nasıl kuracağınızı adım adım anlattık.',
        'og_image' => '/images/blog/git-deploy-ile-canli-site-guncelleme.svg',
        'published_days_ago' => 13,
    ],
    [
        'slug' => 'google-drive-sunucu-yedekleme-rehberi',
        'file' => '07-google-drive-sunucu-yedekleme-rehberi.md',
        'category_slug' => 'security',
        'title' => 'Google Drive ile sunucu yedekleme: dosya ve veritabanı stratejisi',
        'meta_title' => 'Sunucu yedekleme Google Drive — hosting paneli ile otomatik backup',
        'meta_description' => 'Yerel yedek yetmez: Google Drive\'a otomatik sunucu yedekleme, saklama süresi, şifreleme ve felaket kurtarma senaryoları.',
        'excerpt' => '“Yedek aldım” demek bazen sadece aynı diskte kopya tutmak demek. Buluta giden otomatik yedekleme neden şart?',
        'og_image' => '/images/blog/google-drive-sunucu-yedekleme-rehberi.svg',
        'published_days_ago' => 10,
    ],
    [
        'slug' => 'web-ajansi-coklu-site-yonetimi',
        'file' => '08-web-ajansi-coklu-site-yonetimi.md',
        'category_slug' => 'scaling',
        'title' => 'Web ajansları için çoklu site yönetimi: tek panelden onlarca proje',
        'meta_title' => 'Ajans hosting paneli — çoklu site ve müşteri yönetimi rehberi',
        'meta_description' => 'Freelancer ve ajanslar için tek sunucuda onlarca müşteri sitesi: izolasyon, white-label panel, faturalandırma ve operasyon ipuçları.',
        'excerpt' => 'Her müşteri için ayrı hosting hesabı açmak hem pahalı hem yorucu. Tek VPS ve tek panelle nasıl ölçeklenirsiniz?',
        'og_image' => '/images/blog/web-ajansi-coklu-site-yonetimi.svg',
        'published_days_ago' => 7,
    ],
    [
        'slug' => 'ubuntu-22-04-web-sunucu-kurulum-checklist',
        'file' => '09-ubuntu-22-04-web-sunucu-kurulum-checklist.md',
        'category_slug' => 'hosting-migration',
        'title' => 'Ubuntu 22.04 web sunucu kurulumu: eksiksiz kontrol listesi',
        'meta_title' => 'Ubuntu 22.04 web sunucu kurulumu — Nginx, PHP, MariaDB checklist',
        'meta_description' => 'Sıfırdan Ubuntu 22.04 LTS web sunucusu: kullanıcı oluşturma, SSH, firewall, Nginx, PHP-FPM, MariaDB ve hosting paneli kurulumu.',
        'excerpt' => 'Yeni bir VPS aldınız; şimdi ne? Ubuntu 22.04 üzerinde üretime hazır web sunucusu için adım adım checklist.',
        'og_image' => '/images/blog/ubuntu-22-04-web-sunucu-kurulum-checklist.svg',
        'published_days_ago' => 4,
    ],
    [
        'slug' => 'php-surumu-degistirme-performans',
        'file' => '10-php-surumu-degistirme-performans.md',
        'category_slug' => 'hosting-migration',
        'title' => 'PHP sürümü değiştirme ve performans: hosting panelinde pratik rehber',
        'meta_title' => 'PHP sürümü değiştirme — PHP 8.2/8.3 performans ve uyumluluk rehberi',
        'meta_description' => 'Site başına PHP sürümü seçmek, OPcache ayarları ve eski WordPress/Laravel projelerinde güvenli geçiş. Panel üzerinden nasıl yönetilir?',
        'excerpt' => 'PHP 7.4 desteği bitti; ama her site aynı anda PHP 8’e geçemez. Site bazlı sürüm yönetimi ve performans ipuçları.',
        'og_image' => '/images/blog/php-surumu-degistirme-performans.svg',
        'published_days_ago' => 1,
    ],
];
