<?php

/**
 * Popüler domain kayıt firmaları — transfer ve NS yönetimi rehberi için.
 */
return [
    'providers' => [
        [
            'id' => 'godaddy',
            'name' => 'GoDaddy',
            'website' => 'https://www.godaddy.com',
            'transfer_url' => 'https://dcc.godaddy.com/control/portfolio',
            'auth_code_help' => 'Domain ayarları → Transfer veya Kilit → EPP / Auth kodu',
            'ns_help' => 'DNS Yönetimi → Nameservers → Özel nameserver',
            'countries' => ['global'],
        ],
        [
            'id' => 'namecheap',
            'name' => 'Namecheap',
            'website' => 'https://www.namecheap.com',
            'transfer_url' => 'https://ap.www.namecheap.com/domains/transfer/',
            'auth_code_help' => 'Domain List → Manage → Sharing & Transfer → Auth Code',
            'ns_help' => 'Advanced DNS → Nameservers → Custom DNS',
            'countries' => ['global'],
        ],
        [
            'id' => 'cloudflare',
            'name' => 'Cloudflare Registrar',
            'website' => 'https://www.cloudflare.com/products/registrar/',
            'transfer_url' => 'https://dash.cloudflare.com/',
            'auth_code_help' => 'Domain → Transfer → Auth code',
            'ns_help' => 'DNS → Nameservers',
            'countries' => ['global'],
        ],
        [
            'id' => 'google',
            'name' => 'Google Domains / Squarespace',
            'website' => 'https://domains.squarespace.com',
            'transfer_url' => 'https://domains.squarespace.com/',
            'auth_code_help' => 'Domain settings → Transfer out → Authorization code',
            'ns_help' => 'DNS settings → Custom nameservers',
            'countries' => ['global'],
        ],
        [
            'id' => 'natro',
            'name' => 'Natro',
            'website' => 'https://www.natro.com',
            'transfer_url' => 'https://www.natro.com/domain-transfer',
            'auth_code_help' => 'Alan Adlarım → Transfer → Auth (EPP) kodu',
            'ns_help' => 'DNS Yönetimi → Nameserver değiştir',
            'countries' => ['TR'],
        ],
        [
            'id' => 'turhost',
            'name' => 'Turhost',
            'website' => 'https://www.turhost.com',
            'transfer_url' => 'https://www.turhost.com/domain-transfer',
            'auth_code_help' => 'Müşteri paneli → Domain → Transfer kodu (EPP)',
            'ns_help' => 'DNS Yönetimi → Nameserver',
            'countries' => ['TR'],
        ],
        [
            'id' => 'isimtescil',
            'name' => 'İsimtescil',
            'website' => 'https://www.isimtescil.net',
            'transfer_url' => 'https://www.isimtescil.net/domain-transfer',
            'auth_code_help' => 'Domain yönetimi → Transfer → Auth kodu talep et',
            'ns_help' => 'DNS → Nameserver ayarları',
            'countries' => ['TR'],
        ],
        [
            'id' => 'nictr',
            'name' => 'TRABİS / Nic.tr (.tr)',
            'website' => 'https://www.nic.tr',
            'transfer_url' => 'https://www.nic.tr',
            'auth_code_help' => '.tr transferleri yetkili kayıt kuruluşu üzerinden yapılır',
            'ns_help' => 'Kayıt kuruluşunuzun panelinden NS güncellemesi',
            'countries' => ['TR'],
        ],
        [
            'id' => 'hostinger',
            'name' => 'Hostinger',
            'website' => 'https://www.hostinger.com',
            'transfer_url' => 'https://hpanel.hostinger.com/domains',
            'auth_code_help' => 'Domains → Transfer → Authorization code',
            'ns_help' => 'DNS / Nameservers → Change nameservers',
            'countries' => ['global'],
        ],
        [
            'id' => 'other',
            'name' => 'Diğer / Bilinmiyor',
            'website' => null,
            'transfer_url' => null,
            'auth_code_help' => 'Mevcut kayıt firmanızın panelinden EPP / Auth kodu alın',
            'ns_help' => 'Nameserver ayarlarını mevcut firmanızın DNS panelinden güncelleyin',
            'countries' => ['global', 'TR'],
        ],
    ],
];
